"""
AutoApplier — PDF Export (reportlab)
Converts plain-text resume / cover-letter content to styled PDFs.
Falls back to UTF-8 bytes when reportlab is unavailable.
"""
from __future__ import annotations
import io
from datetime import datetime
from typing import Optional


def _rl() -> bool:
    try:
        import reportlab  # noqa: F401
        return True
    except ImportError:
        return False


def generate_resume_pdf(content: str, candidate_name: str = "Resume") -> bytes:
    if not _rl():
        return content.encode("utf-8")

    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER
    from reportlab.lib.pagesizes import LETTER
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=LETTER,
        leftMargin=0.75*inch, rightMargin=0.75*inch,
        topMargin=0.75*inch,  bottomMargin=0.75*inch,
    )

    styles = getSampleStyleSheet()
    name_style = ParagraphStyle(
        "Name", parent=styles["Normal"],
        fontSize=22, fontName="Helvetica-Bold",
        textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=4, alignment=TA_CENTER,
    )
    section_style = ParagraphStyle(
        "Section", parent=styles["Normal"],
        fontSize=11, fontName="Helvetica-Bold",
        textColor=colors.HexColor("#4f46e5"),
        spaceBefore=10, spaceAfter=3,
    )
    body_style = ParagraphStyle(
        "Body", parent=styles["Normal"],
        fontSize=10, fontName="Helvetica",
        textColor=colors.HexColor("#374151"),
        spaceAfter=2, leading=13,
    )
    bullet_style = ParagraphStyle(
        "Bullet", parent=body_style, leftIndent=14,
    )
    footer_style = ParagraphStyle(
        "Footer", parent=body_style,
        fontSize=8, textColor=colors.HexColor("#9ca3af"),
        alignment=TA_CENTER,
    )

    SECTION_KW = {
        "PROFESSIONAL SUMMARY","SUMMARY","SKILLS","PROFESSIONAL EXPERIENCE",
        "EXPERIENCE","EDUCATION","CERTIFICATIONS","PROJECTS","AWARDS","PUBLICATIONS",
    }

    story = []
    lines = content.split("\n")
    i = 0

    # First non-empty line → name
    while i < len(lines) and not lines[i].strip():
        i += 1
    if i < len(lines):
        story.append(Paragraph(lines[i].strip(), name_style))
        story.append(HRFlowable(
            width="100%", thickness=2,
            color=colors.HexColor("#4f46e5"), spaceAfter=6,
        ))
        i += 1

    while i < len(lines):
        line    = lines[i]
        stripped = line.strip()
        if not stripped:
            story.append(Spacer(1, 3))
        elif stripped.upper() in SECTION_KW or (stripped.isupper() and 3 < len(stripped) < 50):
            story.append(Paragraph(stripped, section_style))
            story.append(HRFlowable(
                width="100%", thickness=0.5,
                color=colors.HexColor("#e5e7eb"), spaceAfter=3,
            ))
        elif stripped.startswith("•") or stripped.startswith("-"):
            story.append(Paragraph("• " + stripped.lstrip("•- "), bullet_style))
        else:
            story.append(Paragraph(stripped, body_style))
        i += 1

    story.append(Spacer(1, 18))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#d1d5db")))
    story.append(Paragraph(
        f"Generated by AutoApplier · {datetime.now().strftime('%B %d, %Y')}",
        footer_style,
    ))
    doc.build(story)
    return buf.getvalue()


def generate_cover_letter_pdf(
    content: str,
    candidate_name: str = "",
    company_name: str = "",
    job_title: str = "",
) -> bytes:
    if not _rl():
        return content.encode("utf-8")

    from reportlab.lib import colors
    from reportlab.lib.enums import TA_JUSTIFY, TA_RIGHT
    from reportlab.lib.pagesizes import LETTER
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=LETTER,
        leftMargin=inch, rightMargin=inch,
        topMargin=inch,  bottomMargin=inch,
    )
    styles = getSampleStyleSheet()

    hdr = ParagraphStyle("Hdr", parent=styles["Normal"],
        fontSize=18, fontName="Helvetica-Bold",
        textColor=colors.HexColor("#1a1a2e"), spaceAfter=2)
    meta = ParagraphStyle("Meta", parent=styles["Normal"],
        fontSize=10, fontName="Helvetica",
        textColor=colors.HexColor("#6b7280"), spaceAfter=2)
    body = ParagraphStyle("Body", parent=styles["Normal"],
        fontSize=11, fontName="Helvetica",
        textColor=colors.HexColor("#1f2937"),
        leading=18, spaceAfter=10, alignment=TA_JUSTIFY)
    date_sty = ParagraphStyle("Date", parent=meta,
        alignment=TA_RIGHT, spaceAfter=20)
    footer_sty = ParagraphStyle("Footer", parent=meta,
        fontSize=8, textColor=colors.HexColor("#9ca3af"))

    story = []
    if candidate_name:
        story.append(Paragraph(candidate_name, hdr))
    if job_title and company_name:
        story.append(Paragraph(f"Applying for: {job_title} at {company_name}", meta))
    story.append(HRFlowable(
        width="100%", thickness=2,
        color=colors.HexColor("#4f46e5"), spaceAfter=14,
    ))
    story.append(Paragraph(datetime.now().strftime("%B %d, %Y"), date_sty))

    for para in content.split("\n\n"):
        text = " ".join(l.strip() for l in para.split("\n") if l.strip())
        if text:
            story.append(Paragraph(text, body))

    story.append(Spacer(1, 28))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#d1d5db")))
    story.append(Paragraph(
        f"Generated by AutoApplier · {datetime.now().strftime('%B %d, %Y')}",
        footer_sty,
    ))
    doc.build(story)
    return buf.getvalue()


# ── Convenience wrappers ──────────────────────────────────────────────────────

def resume_text_to_pdf_bytes(text: str, name: str = "Candidate") -> bytes:
    return generate_resume_pdf(text, candidate_name=name)


def cover_letter_to_pdf_bytes(
    text: str, name: str = "", company: str = "", job_title: str = ""
) -> bytes:
    return generate_cover_letter_pdf(
        text, candidate_name=name, company_name=company, job_title=job_title
    )
